/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRemediesRouteImport } from './routes/app.remedies'
import { Route as AppPatientRouteImport } from './routes/app.patient'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as AppPatientsIndexRouteImport } from './routes/app.patients.index'
import { Route as AppPatientsNewRouteImport } from './routes/app.patients.new'
import { Route as AppPatientsPatientIdRouteImport } from './routes/app.patients.$patientId'
import { Route as ApiPublicHooksFollowUpRemindersRouteImport } from './routes/api/public/hooks/follow-up-reminders'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRemediesRoute = AppRemediesRouteImport.update({
  id: '/remedies',
  path: '/remedies',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientRoute = AppPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsNewRoute = AppPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsPatientIdRoute = AppPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksFollowUpRemindersRoute =
  ApiPublicHooksFollowUpRemindersRouteImport.update({
    id: '/api/public/hooks/follow-up-reminders',
    path: '/api/public/hooks/follow-up-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/patient': typeof AppPatientRoute
  '/app/remedies': typeof AppRemediesRoute
  '/app/': typeof AppIndexRoute
  '/app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/app/patients/new': typeof AppPatientsNewRoute
  '/app/patients/': typeof AppPatientsIndexRoute
  '/api/public/hooks/follow-up-reminders': typeof ApiPublicHooksFollowUpRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/patient': typeof AppPatientRoute
  '/app/remedies': typeof AppRemediesRoute
  '/app': typeof AppIndexRoute
  '/app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/app/patients/new': typeof AppPatientsNewRoute
  '/app/patients': typeof AppPatientsIndexRoute
  '/api/public/hooks/follow-up-reminders': typeof ApiPublicHooksFollowUpRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/patient': typeof AppPatientRoute
  '/app/remedies': typeof AppRemediesRoute
  '/app/': typeof AppIndexRoute
  '/app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/app/patients/new': typeof AppPatientsNewRoute
  '/app/patients/': typeof AppPatientsIndexRoute
  '/api/public/hooks/follow-up-reminders': typeof ApiPublicHooksFollowUpRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/appointments'
    | '/app/patient'
    | '/app/remedies'
    | '/app/'
    | '/app/patients/$patientId'
    | '/app/patients/new'
    | '/app/patients/'
    | '/api/public/hooks/follow-up-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/appointments'
    | '/app/patient'
    | '/app/remedies'
    | '/app'
    | '/app/patients/$patientId'
    | '/app/patients/new'
    | '/app/patients'
    | '/api/public/hooks/follow-up-reminders'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/appointments'
    | '/app/patient'
    | '/app/remedies'
    | '/app/'
    | '/app/patients/$patientId'
    | '/app/patients/new'
    | '/app/patients/'
    | '/api/public/hooks/follow-up-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksFollowUpRemindersRoute: typeof ApiPublicHooksFollowUpRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/remedies': {
      id: '/app/remedies'
      path: '/remedies'
      fullPath: '/app/remedies'
      preLoaderRoute: typeof AppRemediesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patient': {
      id: '/app/patient'
      path: '/patient'
      fullPath: '/app/patient'
      preLoaderRoute: typeof AppPatientRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/': {
      id: '/app/patients/'
      path: '/patients'
      fullPath: '/app/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/new': {
      id: '/app/patients/new'
      path: '/patients/new'
      fullPath: '/app/patients/new'
      preLoaderRoute: typeof AppPatientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/$patientId': {
      id: '/app/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/app/patients/$patientId'
      preLoaderRoute: typeof AppPatientsPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/follow-up-reminders': {
      id: '/api/public/hooks/follow-up-reminders'
      path: '/api/public/hooks/follow-up-reminders'
      fullPath: '/api/public/hooks/follow-up-reminders'
      preLoaderRoute: typeof ApiPublicHooksFollowUpRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppPatientRoute: typeof AppPatientRoute
  AppRemediesRoute: typeof AppRemediesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPatientsPatientIdRoute: typeof AppPatientsPatientIdRoute
  AppPatientsNewRoute: typeof AppPatientsNewRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppPatientRoute: AppPatientRoute,
  AppRemediesRoute: AppRemediesRoute,
  AppIndexRoute: AppIndexRoute,
  AppPatientsPatientIdRoute: AppPatientsPatientIdRoute,
  AppPatientsNewRoute: AppPatientsNewRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksFollowUpRemindersRoute: ApiPublicHooksFollowUpRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
